#### I want to make a dataframe which will have a series of car collections.     
It will have 5 columns: **number, manufacturer, model, max speed, power**.

In [169]:
import numpy as np
import pandas as pd
from io import StringIO

In [170]:
c1=["0007","Aston Martin","DB5",233,282]
c2=["2207","Mercedes Benz","Gullwing",260,215]
c3=["1001","Ford Mustang","Boss 429",200,375]
c4=["8888","Porsche","918 Spyder",345,887]
c5=["2026","Ford Mustang","Fastback",193,271]
c6=["9247","Porsche","Macan",230,402]
c7=["7145","Bentley","Continental GT",335,659]
c8=["4997","Land Rover","Defender",240,296]
car_ar=np.array([c1,c2,c3,c4,c5,c6,c7,c8])

In [171]:
car_df=pd.DataFrame(car_ar,columns=["number","manufacturer","model","max speed","power"])
car_df.to_csv("FILES_JUPYTER/car collections.csv",index=False)

In [216]:
print(car_df)
print(car_df.info())

  number   manufacturer           model max speed power
0   0007   Aston Martin             DB5       233   282
1   2207  Mercedes Benz        Gullwing       260   215
2   1001   Ford Mustang        Boss 429       200   375
3   8888        Porsche      918 Spyder       345   887
4   2026   Ford Mustang        Fastback       193   271
5   9247        Porsche           Macan       230   402
6   7145        Bentley  Continental GT       335   659
7   4997     Land Rover        Defender       240   296
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 8 entries, 0 to 7
Data columns (total 5 columns):
 #   Column        Non-Null Count  Dtype 
---  ------        --------------  ----- 
 0   number        8 non-null      object
 1   manufacturer  8 non-null      object
 2   model         8 non-null      object
 3   max speed     8 non-null      object
 4   power         8 non-null      object
dtypes: object(5)
memory usage: 452.0+ bytes
None


In [220]:
car_csv=pd.read_csv("FILES_JUPYTER/car collections.csv")
print(car_csv.info())

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 8 entries, 0 to 7
Data columns (total 5 columns):
 #   Column        Non-Null Count  Dtype 
---  ------        --------------  ----- 
 0   number        8 non-null      int64 
 1   manufacturer  8 non-null      object
 2   model         8 non-null      object
 3   max speed     8 non-null      int64 
 4   power         8 non-null      int64 
dtypes: int64(3), object(2)
memory usage: 452.0+ bytes
None


### -: *ARRAY* :-

In [174]:
print(car_ar)
print("shape of the array is",car_ar.shape)

[['0007' 'Aston Martin' 'DB5' '233' '282']
 ['2207' 'Mercedes Benz' 'Gullwing' '260' '215']
 ['1001' 'Ford Mustang' 'Boss 429' '200' '375']
 ['8888' 'Porsche' '918 Spyder' '345' '887']
 ['2026' 'Ford Mustang' 'Fastback' '193' '271']
 ['9247' 'Porsche' 'Macan' '230' '402']
 ['7145' 'Bentley' 'Continental GT' '335' '659']
 ['4997' 'Land Rover' 'Defender' '240' '296']]
shape of the array is (8, 5)


In [175]:
car_ar[1::2,1:2]

array([['Mercedes Benz'],
       ['Porsche'],
       ['Porsche'],
       ['Land Rover']], dtype='<U21')

In [176]:
print(car_ar.reshape(4,10))

[['0007' 'Aston Martin' 'DB5' '233' '282' '2207' 'Mercedes Benz'
  'Gullwing' '260' '215']
 ['1001' 'Ford Mustang' 'Boss 429' '200' '375' '8888' 'Porsche'
  '918 Spyder' '345' '887']
 ['2026' 'Ford Mustang' 'Fastback' '193' '271' '9247' 'Porsche' 'Macan'
  '230' '402']
 ['7145' 'Bentley' 'Continental GT' '335' '659' '4997' 'Land Rover'
  'Defender' '240' '296']]


### -: *DataFrame* :-

In [177]:
print(car_df.head())
print("-"*50)
print(car_df.info())

  number   manufacturer       model max speed power
0   0007   Aston Martin         DB5       233   282
1   2207  Mercedes Benz    Gullwing       260   215
2   1001   Ford Mustang    Boss 429       200   375
3   8888        Porsche  918 Spyder       345   887
4   2026   Ford Mustang    Fastback       193   271
--------------------------------------------------
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 8 entries, 0 to 7
Data columns (total 5 columns):
 #   Column        Non-Null Count  Dtype 
---  ------        --------------  ----- 
 0   number        8 non-null      object
 1   manufacturer  8 non-null      object
 2   model         8 non-null      object
 3   max speed     8 non-null      object
 4   power         8 non-null      object
dtypes: object(5)
memory usage: 452.0+ bytes
None


In [178]:
car_df.describe()

,number,manufacturer,model,max speed,power
count,8,8,8,8,8
unique,8,6,8,8,8
top,0007,Ford Mustang,DB5,233,282
freq,1,2,1,1,1


In [179]:
print(car_df["model"])
print(type(car_df["model"]))

0               DB5
1          Gullwing
2          Boss 429
3        918 Spyder
4          Fastback
5             Macan
6    Continental GT
7          Defender
Name: model, dtype: object
<class 'pandas.core.series.Series'>


In [180]:
print(car_df.iloc[2:4,1:2])
print("-"*50)
print(car_df.iloc[0:,4])
print("-"*50)
print(car_df.loc[[0,1,2]])
print("-"*50)
print(car_df.iloc[1])

   manufacturer
2  Ford Mustang
3       Porsche
--------------------------------------------------
0    282
1    215
2    375
3    887
4    271
5    402
6    659
7    296
Name: power, dtype: object
--------------------------------------------------
  number   manufacturer     model max speed power
0   0007   Aston Martin       DB5       233   282
1   2207  Mercedes Benz  Gullwing       260   215
2   1001   Ford Mustang  Boss 429       200   375
--------------------------------------------------
number                   2207
manufacturer    Mercedes Benz
model                Gullwing
max speed                 260
power                     215
Name: 1, dtype: object


In [181]:
print(car_df.iloc[0:,1::2].values)
# converts dataframe to array
print("_"*50)
print((car_df.iloc[0:,1::2].values).shape)

[['Aston Martin' '233']
 ['Mercedes Benz' '260']
 ['Ford Mustang' '200']
 ['Porsche' '345']
 ['Ford Mustang' '193']
 ['Porsche' '230']
 ['Bentley' '335']
 ['Land Rover' '240']]
__________________________________________________
(8, 2)


In [182]:
car_df

,number,manufacturer,model,max speed,power
0,0007,Aston Martin,DB5,233,282
1,2207,Mercedes Benz,Gullwing,260,215
2,1001,Ford Mustang,Boss 429,200,375
3,8888,Porsche,918 Spyder,345,887
4,2026,Ford Mustang,Fastback,193,271
5,9247,Porsche,Macan,230,402
6,7145,Bentley,Continental GT,335,659
7,4997,Land Rover,Defender,240,296


In [183]:
'''new_lst=[["1881","Horny Bunny","DaddyX69",222,458]]
nrow1=pd.DataFrame(new_lst,index=[8],columns=["number","manufacturer","model","max speed","power"])
car_df=pd.concat([car_df,nrow1])'''
# New row added

'new_lst=[["1881","Horny Bunny","DaddyX69",222,458]]\nnrow1=pd.DataFrame(new_lst,index=[8],columns=["number","manufacturer","model","max speed","power"])\ncar_df=pd.concat([car_df,nrow1])'

In [184]:
#new_dit={}
'''nrow2=pd.DataFrame({},index=[9])
car_df=pd.concat([car_df,nrow2])'''
'''to add a nan row in a dataframe, you can input a empty list or 
    dictionary and rewrite the dataframe'''
# Added a new nan row
car_df

,number,manufacturer,model,max speed,power
0,0007,Aston Martin,DB5,233,282
1,2207,Mercedes Benz,Gullwing,260,215
2,1001,Ford Mustang,Boss 429,200,375
3,8888,Porsche,918 Spyder,345,887
4,2026,Ford Mustang,Fastback,193,271
5,9247,Porsche,Macan,230,402
6,7145,Bentley,Continental GT,335,659
7,4997,Land Rover,Defender,240,296


In [185]:
'''car_df["Type"]="hello"
print(car_df)'''
# added a new column named "Type"

'car_df["Type"]="hello"\nprint(car_df)'

In [186]:
'''car_df=car_df.drop("Type",axis=1)
car_df'''
#deleted the column named "Type". running this commented code again will show error.

'car_df=car_df.drop("Type",axis=1)\ncar_df'

In [187]:
'''car_df=car_df.drop([8,9])
print(car_df)'''
# deleted 2 rows. running the commented code again will show key error.

'car_df=car_df.drop([8,9])\nprint(car_df)'

In [188]:
car_df

,number,manufacturer,model,max speed,power
0,0007,Aston Martin,DB5,233,282
1,2207,Mercedes Benz,Gullwing,260,215
2,1001,Ford Mustang,Boss 429,200,375
3,8888,Porsche,918 Spyder,345,887
4,2026,Ford Mustang,Fastback,193,271
5,9247,Porsche,Macan,230,402
6,7145,Bentley,Continental GT,335,659
7,4997,Land Rover,Defender,240,296


In [189]:
print(car_df["manufacturer"].value_counts())
print("_"*50)
print(car_df["max speed"].value_counts(normalize=True))
print("_"*50)
print(car_df["power"].value_counts())

manufacturer
Ford Mustang     2
Porsche          2
Aston Martin     1
Mercedes Benz    1
Bentley          1
Land Rover       1
Name: count, dtype: int64
__________________________________________________
max speed
233    0.125
260    0.125
200    0.125
345    0.125
193    0.125
230    0.125
335    0.125
240    0.125
Name: proportion, dtype: float64
__________________________________________________
power
282    1
215    1
375    1
887    1
271    1
402    1
659    1
296    1
Name: count, dtype: int64


In [190]:
car_df["max speed"]==car_df["power"]
#nothing same in 'max speed' and 'power' columns

0    False
1    False
2    False
3    False
4    False
5    False
6    False
7    False
dtype: bool

In [191]:
print(car_df["power"].unique().reshape(2,4))
print("_"*50)
print(car_df["manufacturer"].nunique())

[['282' '215' '375' '887']
 ['271' '402' '659' '296']]
__________________________________________________
6


In [192]:
print(car_df.to_numpy().reshape(4,10))
# converts dataframe to array

[['0007' 'Aston Martin' 'DB5' '233' '282' '2207' 'Mercedes Benz'
  'Gullwing' '260' '215']
 ['1001' 'Ford Mustang' 'Boss 429' '200' '375' '8888' 'Porsche'
  '918 Spyder' '345' '887']
 ['2026' 'Ford Mustang' 'Fastback' '193' '271' '9247' 'Porsche' 'Macan'
  '230' '402']
 ['7145' 'Bentley' 'Continental GT' '335' '659' '4997' 'Land Rover'
  'Defender' '240' '296']]


In [193]:
dit={"C0":[12,64,31,60,80],
     "C1":[35,71,29,49,84],
     "C2":[30,64,91,53,64],
     "C3":[15,12,93,np.nan,85],
     "C4":[63,52,95,31,63]}
dit_df=pd.DataFrame(dit)
dit_df.to_csv("FILES_JUPYTER/numbers.csv",index=False)

In [194]:
arr2=np.array(list(dit.values()))
print(arr2)         #the columns are rows and the rows aere columns
print("_"*50)
arr3=np.array(list(dit.values())).T
# using '.T' just changes it vice-versa
print(arr3)

[[12. 64. 31. 60. 80.]
 [35. 71. 29. 49. 84.]
 [30. 64. 91. 53. 64.]
 [15. 12. 93. nan 85.]
 [63. 52. 95. 31. 63.]]
__________________________________________________
[[12. 35. 30. 15. 63.]
 [64. 71. 64. 12. 52.]
 [31. 29. 91. 93. 95.]
 [60. 49. 53. nan 31.]
 [80. 84. 64. 85. 63.]]


### -: *CSV* :-
##### Two csv files has been imported in this notebook:
##### (1) car collection.csv
##### (2) numbers.csv

In [195]:
print(car_df)
print("-"*75)
print(car_ar)
print("-"*75)
print(dit)
print("-"*75)
print(dit_df)

  number   manufacturer           model max speed power
0   0007   Aston Martin             DB5       233   282
1   2207  Mercedes Benz        Gullwing       260   215
2   1001   Ford Mustang        Boss 429       200   375
3   8888        Porsche      918 Spyder       345   887
4   2026   Ford Mustang        Fastback       193   271
5   9247        Porsche           Macan       230   402
6   7145        Bentley  Continental GT       335   659
7   4997     Land Rover        Defender       240   296
---------------------------------------------------------------------------
[['0007' 'Aston Martin' 'DB5' '233' '282']
 ['2207' 'Mercedes Benz' 'Gullwing' '260' '215']
 ['1001' 'Ford Mustang' 'Boss 429' '200' '375']
 ['8888' 'Porsche' '918 Spyder' '345' '887']
 ['2026' 'Ford Mustang' 'Fastback' '193' '271']
 ['9247' 'Porsche' 'Macan' '230' '402']
 ['7145' 'Bentley' 'Continental GT' '335' '659']
 ['4997' 'Land Rover' 'Defender' '240' '296']]
---------------------------------------------------

In [196]:
new1=pd.DataFrame([],index=[5])
dit_df=pd.concat([dit_df,new1])
print(dit_df)
'''dit_df=dit_df.drop([5])     #To delete the nan row just added above
print(dit_df)'''

     C0    C1    C2    C3    C4
0  12.0  35.0  30.0  15.0  63.0
1  64.0  71.0  64.0  12.0  52.0
2  31.0  29.0  91.0  93.0  95.0
3  60.0  49.0  53.0   NaN  31.0
4  80.0  84.0  64.0  85.0  63.0
5   NaN   NaN   NaN   NaN   NaN


'dit_df=dit_df.drop([5])     #To delete the nan row just added above\nprint(dit_df)'

In [197]:
l1=[45,np.nan,81,30,72]
new2=pd.DataFrame([l1],index=[6],columns=["C0","C1","C2","C3","C4"])
dit_df=pd.concat([dit_df,new2])
print(dit_df)

     C0    C1    C2    C3    C4
0  12.0  35.0  30.0  15.0  63.0
1  64.0  71.0  64.0  12.0  52.0
2  31.0  29.0  91.0  93.0  95.0
3  60.0  49.0  53.0   NaN  31.0
4  80.0  84.0  64.0  85.0  63.0
5   NaN   NaN   NaN   NaN   NaN
6  45.0   NaN  81.0  30.0  72.0


In [198]:
dit_df.to_csv("FILES_JUPYTER/numbers and nan.csv",index=False)

In [199]:
pd.read_csv("FILES_JUPYTER/sep.txt",sep=r'\s+')

,name,class,marks
0,abdul,4,36
1,ramu,7,54
2,rekha,9,71
3,shyam,8,50
4,vinay,5,15
5,sunil,10,70


In [200]:
pd.read_csv("FILES_JUPYTER/numbers.csv")

,C0,C1,C2,C3,C4
0,12,35,30,15.0,63
1,64,71,64,12.0,52
2,31,29,91,93.0,95
3,60,49,53,NaN,31
4,80,84,64,85.0,63


In [201]:
pd.read_csv("FILES_JUPYTER/numbers and nan.csv")

,C0,C1,C2,C3,C4
0,12.0,35.0,30.0,15.0,63.0
1,64.0,71.0,64.0,12.0,52.0
2,31.0,29.0,91.0,93.0,95.0
3,60.0,49.0,53.0,NaN,31.0
4,80.0,84.0,64.0,85.0,63.0
5,NaN,NaN,NaN,NaN,NaN
6,45.0,NaN,81.0,30.0,72.0


In [202]:
pd.read_csv("FILES_JUPYTER/numbers and nan.csv",header=3)
# 'header=n' makes the row above the row having index number "n" as the header of the dataframe. 
# It doesn't print the rows above and takes that row values as the column names.

,31.0,29.0,91.0,93.0,95.0
0,60.0,49.0,53.0,NaN,31.0
1,80.0,84.0,64.0,85.0,63.0
2,NaN,NaN,NaN,NaN,NaN
3,45.0,NaN,81.0,30.0,72.0


In [203]:
pd.read_csv("FILES_JUPYTER/numbers and nan.csv",usecols=["C3","C1"])
# It calls the specified columns from the dataframe.

,C1,C3
0,35.0,15.0
1,71.0,12.0
2,29.0,93.0
3,49.0,NaN
4,84.0,85.0
5,NaN,NaN
6,NaN,30.0


In [204]:
pd.read_csv("FILES_JUPYTER/binary_df.csv")

,C1,C2,C3,C4,C5
0,0,1,0,0,1
1,1,1,1,1,1
2,1,0,0,1,1
3,0,0,0,0,0
4,0,1,0,1,0


In [205]:
nan_df=pd.read_csv("FILES_JUPYTER/binary_df.csv",na_values=[0,1])
nan_csv=nan_df.to_csv("FILES_JUPYTER/NAN.csv",index=False)
# NAN.csv has 5 rows and 5 columns, all having nan values only

In [206]:
pd.read_csv("FILES_JUPYTER/NAN.csv")

,C1,C2,C3,C4,C5
0,NaN,NaN,NaN,NaN,NaN
1,NaN,NaN,NaN,NaN,NaN
2,NaN,NaN,NaN,NaN,NaN
3,NaN,NaN,NaN,NaN,NaN
4,NaN,NaN,NaN,NaN,NaN


In [207]:
pd.read_csv("FILES_JUPYTER/NAN.csv",header=3)

,Unnamed: 0,Unnamed: 1,Unnamed: 2,Unnamed: 3,Unnamed: 4
0,NaN,NaN,NaN,NaN,NaN
1,NaN,NaN,NaN,NaN,NaN


In [208]:
pd.read_csv("FILES_JUPYTER/car collections.csv")

,number,manufacturer,model,max speed,power
0,7,Aston Martin,DB5,233,282
1,2207,Mercedes Benz,Gullwing,260,215
2,1001,Ford Mustang,Boss 429,200,375
3,8888,Porsche,918 Spyder,345,887
4,2026,Ford Mustang,Fastback,193,271
5,9247,Porsche,Macan,230,402
6,7145,Bentley,Continental GT,335,659
7,4997,Land Rover,Defender,240,296


In [209]:
print(pd.read_csv("FILES_JUPYTER/car collections.csv",header=None))
# 'header=None' removes the header and shows column numbers

        0              1               2          3      4
0  number   manufacturer           model  max speed  power
1    0007   Aston Martin             DB5        233    282
2    2207  Mercedes Benz        Gullwing        260    215
3    1001   Ford Mustang        Boss 429        200    375
4    8888        Porsche      918 Spyder        345    887
5    2026   Ford Mustang        Fastback        193    271
6    9247        Porsche           Macan        230    402
7    7145        Bentley  Continental GT        335    659
8    4997     Land Rover        Defender        240    296


In [210]:
no_df=pd.read_csv("FILES_JUPYTER/numbers.csv",
                  dtype={"C0":"int","C2":"object"})
print(no_df.info())
print(no_df)
# dtype converts the type of the specified column.
# But it can not convert the type of a column if it has nan value.
# Columns having nan value will always remain as float type.

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5 entries, 0 to 4
Data columns (total 5 columns):
 #   Column  Non-Null Count  Dtype  
---  ------  --------------  -----  
 0   C0      5 non-null      int64  
 1   C1      5 non-null      int64  
 2   C2      5 non-null      object 
 3   C3      4 non-null      float64
 4   C4      5 non-null      int64  
dtypes: float64(1), int64(3), object(1)
memory usage: 332.0+ bytes
None
   C0  C1  C2    C3  C4
0  12  35  30  15.0  63
1  64  71  64  12.0  52
2  31  29  91  93.0  95
3  60  49  53   NaN  31
4  80  84  64  85.0  63


In [211]:
print(no_df.dtypes)
print(pd.read_csv("FILES_JUPYTER/numbers.csv").info())
# Original data not changed

C0      int64
C1      int64
C2     object
C3    float64
C4      int64
dtype: object
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5 entries, 0 to 4
Data columns (total 5 columns):
 #   Column  Non-Null Count  Dtype  
---  ------  --------------  -----  
 0   C0      5 non-null      int64  
 1   C1      5 non-null      int64  
 2   C2      5 non-null      int64  
 3   C3      4 non-null      float64
 4   C4      5 non-null      int64  
dtypes: float64(1), int64(4)
memory usage: 332.0 bytes
None


In [212]:
print(nan_df.isnull().sum())

C1    5
C2    5
C3    5
C4    5
C5    5
dtype: int64


In [213]:
pd.read_csv("FILES_JUPYTER/car collections.csv")

,number,manufacturer,model,max speed,power
0,7,Aston Martin,DB5,233,282
1,2207,Mercedes Benz,Gullwing,260,215
2,1001,Ford Mustang,Boss 429,200,375
3,8888,Porsche,918 Spyder,345,887
4,2026,Ford Mustang,Fastback,193,271
5,9247,Porsche,Macan,230,402
6,7145,Bentley,Continental GT,335,659
7,4997,Land Rover,Defender,240,296


In [221]:
pd.read_csv("FILES_JUPYTER/car collections.csv",index_col=["number"],
            usecols=["number","model","max speed"],
            dtype={"number":"str"})

,model,max speed
number,,
0007,DB5,233
2207,Gullwing,260
1001,Boss 429,200
8888,918 Spyder,345
2026,Fastback,193
9247,Macan,230
7145,Continental GT,335
4997,Defender,240


In [231]:
pd.read_csv("FILES_JUPYTER/car collections.csv",dtype={"number":str}).info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 8 entries, 0 to 7
Data columns (total 5 columns):
 #   Column        Non-Null Count  Dtype 
---  ------        --------------  ----- 
 0   number        8 non-null      object
 1   manufacturer  8 non-null      object
 2   model         8 non-null      object
 3   max speed     8 non-null      int64 
 4   power         8 non-null      int64 
dtypes: int64(2), object(3)
memory usage: 452.0+ bytes


In [230]:
pd.read_csv("FILES_JUPYTER/car collections.csv",dtype={"number":str})

,number,manufacturer,model,max speed,power
0,0007,Aston Martin,DB5,233,282
1,2207,Mercedes Benz,Gullwing,260,215
2,1001,Ford Mustang,Boss 429,200,375
3,8888,Porsche,918 Spyder,345,887
4,2026,Ford Mustang,Fastback,193,271
5,9247,Porsche,Macan,230,402
6,7145,Bentley,Continental GT,335,659
7,4997,Land Rover,Defender,240,296


In [236]:
number_df=pd.read_csv("FILES_JUPYTER/car collections.csv",
                      index_col=["number"],dtype={"number":str})
print(number_df)

         manufacturer           model  max speed  power
number                                                 
0007     Aston Martin             DB5        233    282
2207    Mercedes Benz        Gullwing        260    215
1001     Ford Mustang        Boss 429        200    375
8888          Porsche      918 Spyder        345    887
2026     Ford Mustang        Fastback        193    271
9247          Porsche           Macan        230    402
7145          Bentley  Continental GT        335    659
4997       Land Rover        Defender        240    296


In [237]:
number_df.loc["0007"]

manufacturer    Aston Martin
model                    DB5
max speed                233
power                    282
Name: 0007, dtype: object