In [1]:
import numpy as np
import pandas as pd

In [2]:
dit={"C0":[12,64,31,60,80],"C1":[35,71,29,49,84],"C2":[30,64,91,53,64],"C3":[15,12,93,np.nan,85],"C4":[63,52,95,31,63]}
df=pd.DataFrame(dit)

In [3]:
print(df)

   C0  C1  C2    C3  C4
0  12  35  30  15.0  63
1  64  71  64  12.0  52
2  31  29  91  93.0  95
3  60  49  53   NaN  31
4  80  84  64  85.0  63


In [4]:
ar=df.to_numpy()        # converting dataframe to array
ar

array([[12., 35., 30., 15., 63.],
       [64., 71., 64., 12., 52.],
       [31., 29., 91., 93., 95.],
       [60., 49., 53., nan, 31.],
       [80., 84., 64., 85., 63.]])

In [5]:
print(ar.shape)

(5, 5)


In [6]:
print(ar[2:,2:])
print("-"*50)
print(ar[1:4,1:4])
print("-"*50)
print(ar[1:4,0:])

[[91. 93. 95.]
 [53. nan 31.]
 [64. 85. 63.]]
--------------------------------------------------
[[71. 64. 12.]
 [29. 91. 93.]
 [49. 53. nan]]
--------------------------------------------------
[[64. 71. 64. 12. 52.]
 [31. 29. 91. 93. 95.]
 [60. 49. 53. nan 31.]]


In [7]:
ar1 = np.array(list(dit.values())).T
print(ar)
print(ar.shape)

[[12. 35. 30. 15. 63.]
 [64. 71. 64. 12. 52.]
 [31. 29. 91. 93. 95.]
 [60. 49. 53. nan 31.]
 [80. 84. 64. 85. 63.]]
(5, 5)
