## USING ARRAY ##

In [24]:
import numpy as np

In [25]:
t=(2,5,7,3)
l=[2,5,7,3]
d={'a':1,'b':3,'c':5}

In [26]:
ar=np.array(l)
ar1=np.array(t)
ar2=np.array(d)
print(ar)
print(ar1)
print(ar2)

[2 5 7 3]
[2 5 7 3]
{'a': 1, 'b': 3, 'c': 5}


In [27]:
type(ar)    #both type is of 1-dimension
type(ar2)

numpy.ndarray

In [28]:
l1=[1,2,3,4]
l2=[4,5,6,7]
l3=[7,8,9,0]
a=np.array([l1,l2,l3])
print(a)

[[1 2 3 4]
 [4 5 6 7]
 [7 8 9 0]]


In [29]:
type(a)     #this is of 2-dimension
a.shape

(3, 4)

In [30]:
print(ar)
ar.shape

[2 5 7 3]


(4,)

In [31]:
for i in a:
    print(i[3])

4
7
0


In [32]:
ar1[2]=1
print(ar1)

[2 5 1 3]


In [33]:
print(a)
a[0:1,1:]

[[1 2 3 4]
 [4 5 6 7]
 [7 8 9 0]]


array([[2, 3, 4]])

In [34]:
a[:,1:2]

array([[2],
       [5],
       [8]])

In [35]:
a[:,::3]

array([[1, 4],
       [4, 7],
       [7, 0]])

In [36]:
for i in a:
    print(i[::3])

[1 4]
[4 7]
[7 0]


In [37]:
a[a<6]

array([1, 2, 3, 4, 4, 5, 0])

In [38]:
print(a.shape)
print(a)

(3, 4)
[[1 2 3 4]
 [4 5 6 7]
 [7 8 9 0]]


In [39]:
a.reshape(4,3)      #4 rows and 3 columns

array([[1, 2, 3],
       [4, 4, 5],
       [6, 7, 7],
       [8, 9, 0]])

In [40]:
r1=np.arange(1,100,4)
print(r1)
print(len(r1))

[ 1  5  9 13 17 21 25 29 33 37 41 45 49 53 57 61 65 69 73 77 81 85 89 93
 97]
25


In [41]:
r1.reshape(5,5)

array([[ 1,  5,  9, 13, 17],
       [21, 25, 29, 33, 37],
       [41, 45, 49, 53, 57],
       [61, 65, 69, 73, 77],
       [81, 85, 89, 93, 97]])

In [42]:
(r1*r1).reshape(5,5)

array([[   1,   25,   81,  169,  289],
       [ 441,  625,  841, 1089, 1369],
       [1681, 2025, 2401, 2809, 3249],
       [3721, 4225, 4761, 5329, 5929],
       [6561, 7225, 7921, 8649, 9409]])

In [43]:
np.ones((3,3))

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [44]:
np.zeros((3,3))

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [45]:
ran=np.random.randint(10,50,60)
ran.reshape(6,10)

array([[42, 46, 29, 27, 49, 47, 19, 13, 35, 47],
       [38, 36, 21, 16, 20, 43, 40, 34, 42, 39],
       [23, 34, 47, 48, 24, 25, 48, 37, 38, 32],
       [11, 42, 33, 19, 48, 25, 25, 12, 40, 26],
       [43, 13, 49, 41, 30, 34, 20, 31, 12, 49],
       [38, 31, 31, 26, 22, 18, 47, 42, 16, 47]])

In [46]:
ran2=np.random.random_sample(9)
print(ran2.reshape(3,3))

[[0.75433177 0.82870394 0.4390985 ]
 [0.3447104  0.19132819 0.47679412]
 [0.82405031 0.9080681  0.52923925]]
